### ISSUE TITLE
Question about pose evaluation - scale consistency?

### ISSUE THREAD

**Issue by kwea123** [JiawangBian/SC-SfMLearner-Release#18]
I found that in the evaluation code, you still scale the output using the GT for every 5-frame snippet:
https://github.com/JiawangBian/SC-SfMLearner-Release/blob/6c6830c5e207718234c4746e2aa5f63913730afa/test_pose.py#L99

However in your work you claim the contribution of scale consistency depth, so I think you need to fix **one global scale** outside the loop and always use the same one, don't you? Am I misunderstanding something?

Also, I don't quite understand the statement you made in section 6.3,

> Although the visual odometry results shown in the main paper is more important

in which sense you mean the results in the main paper are more important?
Thank you.

**Comment by JiawangBian** [comment]
it is evaluation code for 5-frame pose estimation， following existing protocols. However, I didn’t show results of such evaluation in main paper. Instead I evaluated pose network using kitti odometey benchmarks. See “test_vo” instead of “test_pose “. VO (a part of SLAM) is traditional task, and it has direct industry uses. Compared with VO, pose in 5-frame is not meaningful.
