### ISSUE TITLE
Question about median scaling

### ISSUE THREAD

**Issue by hyBlue** [JiawangBian/SC-SfMLearner-Release#19]
Hi, I want to ask the reason why using median scaling during evaluation even though this method can predict scale-consistent depth of images. Is it necessary?

**Comment by Huangying-Zhan** [comment]
Hi @hyBlue, there are two scale issues in monocular training.
(1) Scale ambiguity
In most monocular systems, the predictions are not in metric scale and there is a missing scaling factor to align the predictions to real-world scale.

(2) Scale inconsistency
Since short snippets are used during training, if there is no regularization, the scale ambiguity issue happens to every snippet and we can't ensure the scales for the snippets are consistent.

In this work, we try to solve the scale-consistency issue by regularizing the scales for different snippets should be consistent. However, the scale ambiguity issue still exists and it can't be solved for monocular systems.

Therefore, in order to evaluate the predictions, we still need to use median scaling to align the predictions to real-world scale and compare with ground truth.

**Comment by hyBlue** [comment]
Great, Thank you for your reply.
