### ISSUE TITLE
Why you use cpu in vo

### ISSUE THREAD

**Issue by TopGun666** [JiawangBian/SC-SfMLearner-Release#21]
Hi Jiawang,

I have 2 questions.
 
1. Why do  you chose to use cpu in vo test rather than CUDA as we can see you set whether or not there is a CUDA judgment at the beginning of the program? But...in fact...
https://github.com/JiawangBian/SC-SfMLearner-Release/blob/078f5ae16e16e669170ff162070f0e897108ff57/test_vo.py#L63

2. As u said in ur paper,
> This is the ﬁrst work to show that deep networks trained using monocular video snippets can predict globally scale-consistent camera trajectories over a long video sequence.

however I test vo with both left and right images, their trajectories are the same, and the scale is consistent with groundtruth, about 1705m and 1711m. However, when I set the left images as the trajectory reference, the `Terminal` output shows, both trajectories are only 1591 poses, 50.944m path length. What do you think about it?

> 1591 files to test
100%|█████████████████████████████████████████████████████████████████████████████████████████| 1590/1590 [05:29<00:00,  4.82it/s]
--------------------------------------------------------------------------------
>name:    09G
infos:    1591 poses, 50.944m path length

**Comment by JiawangBian** [comment]
Hey man,
1. GPU is used for model inference.  Concatenating pose results to a long trajectory is very efficient, so using CPU or GPU is both OK.
2. It is a common issue for monocuar systems, well-known as scale ambiguity. You will find that monocular ORB-SLAM also cannot provide a 1700m trajectoy. So you need align the scale to ground truth for evaluation. The 'globally consistent' here means that we only need align one global scale to GT, instead of aligning n scales for n frames.

Regards,
Jiawang

**Comment by TopGun666** [comment]
I see... Thx for ur reply.
