### ISSUE TITLE
Using mask in training 

### ISSUE THREAD

**Issue by leyuan-sun** [JiawangBian/SC-SfMLearner-Release#85]
Why you use mask in training? When we in initial training period, the mask may not be correct, if the mask is not correct, it will degrade the training. Is it correct?

**Comment by leyuan-sun** [comment]
Could you plz answer my question...?

**Comment by JiawangBian** [comment]
Yes, it is correct, but it doesn't matter. You will find that the geometry consistency loss is small from the beginning or quickly drops to a small value so that the weight for most regions is always high. After several epochs, the system can learn correct consistency, so that the training will not be degraded.
